import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getSession } from "@auth0/nextjs-auth0";
import { getRequestContext } from "@/lib/utils";
import { ComponentLibraryProvider } from "@/lib/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  const requestContext = getRequestContext(session);

  const ctwRequestContext = {
    env: process.env.NEXT_PUBLIC_ENV,
    authToken: requestContext.accessToken,
    builderId: requestContext.builderId,
    user: session?.user,
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <ComponentLibraryProvider ctwRequestContext={ctwRequestContext}>
          {children}
        </ComponentLibraryProvider>
      </body>
    </html>
  );
}
